### PR TITLE
Leaflet 0.7

### PR DESCRIPTION
**Pull request by hagai26**
branch leaflet 0.7 version with link to leaflet 1.0 version

### CODE REVIEW

**Comment by ghybs** [comment]
Thank you for the additional PR!

If I understand correctly, I should:
1. Create a new `leaflet-0.7` branch.
2. Have you change this PR to point into `ghybs:leaflet-0.7` branch.
3. Merge the PR?

If I do the command lines and push it directly into the new `leaflet-0.7` branch, will it consider this PR as having been merged?
Sorry I am not very comfortable yet with GitHub…

**Comment by hagai26** [comment]
yes

**Comment by ghybs** [comment]
Ok I just created `leaflet-0.7` branch.

**Comment by ghybs** [comment]
Replaced by PR #7 so that it points into `leaflet-0.7` branch.

**Pull request closed without merging**
